version: '3.9'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=mysql://root:root@split-money-db:3306/split_money
      - JWT_SECRET=your-secret-key
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    command: sh -c "chmod +x /app/init-db.sh && /app/init-db.sh && npm run dev"

  mysql:
    image: mysql:8.0
    container_name: split-money-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: split_money
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
